// Copyright (c) 2026, Lars Brubaker. MIT licensed (see LICENSE).
// Ported from COLMAP (BSD-3-Clause, see THIRD_PARTY_NOTICES.md).
//
// CameraSpecs.Data9: part 9 of the sensor-width table of colmap/sensor/specs.cc
// (makes "yuneec" to "yuneec"). GENERATED by
// scripts/generate-camera-specs.py from the C++ reference; do not edit by hand.

namespace ColmapSharp.Sensor;

public static partial class CameraSpecs
{
	private static void AddMakes9(List<CameraMakeSpecs> specs)
	{
		specs.Add(new CameraMakeSpecs("yuneec", [
			new("e90", 13.2000f),
		]));
	}
}
