#!/usr/bin/env python3
# Generates ColmapSharp/Sensor/CameraSpecs.Data*.cs from COLMAP's sensor/specs.cc (the camera
# sensor-width database, ~4,400 entries). The data is copied verbatim - make, model and
# sensor width in the order specs.cc lists them - so regenerating after a REFERENCE bump is
# the whole port. The output is split into partial files at make boundaries so no file
# exceeds the 800-non-empty-line limit (CLAUDE.md).
#
# Usage: scripts/fetch-reference.sh && python3 scripts/generate-camera-specs.py
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "cpp-reference/src/colmap/sensor/specs.cc"
OUT_DIR = ROOT / "ColmapSharp/Sensor"
MAX_LINES_PER_FILE = 700

MAKE_RE = re.compile(r'auto& make_specs = specs\["([^"\\]*)"\];')
ENTRY_RE = re.compile(r'make_specs\.emplace_back\("([^"\\]*)", ([0-9.]+f)\);')


def parse(text):
    makes = []
    for line in text.splitlines():
        make = MAKE_RE.search(line)
        if make:
            makes.append((make.group(1), []))
            continue
        entry = ENTRY_RE.search(line)
        if entry:
            makes[-1][1].append((entry.group(1), entry.group(2)))
        elif "emplace_back" in line:
            sys.exit(f"unrecognized entry line: {line.strip()}")
    names = [name for name, _ in makes]
    if len(names) != len(set(names)):
        sys.exit("a make appears twice; InitializeCameraSpecs would merge it")
    return makes


def chunk(makes):
    chunks, current, size = [], [], 0
    for make in makes:
        make_size = len(make[1]) + 3
        if current and size + make_size > MAX_LINES_PER_FILE:
            chunks.append(current)
            current, size = [], 0
        current.append(make)
        size += make_size
    if current:
        chunks.append(current)
    return chunks


def write_chunk(index, makes):
    lines = [
        "// Copyright (c) 2026, Lars Brubaker. MIT licensed (see LICENSE).",
        "// Ported from COLMAP (BSD-3-Clause, see THIRD_PARTY_NOTICES.md).",
        "//",
        f"// CameraSpecs.Data{index}: part {index} of the sensor-width table of colmap/sensor/specs.cc",
        f"// (makes \"{makes[0][0]}\" to \"{makes[-1][0]}\"). GENERATED by",
        "// scripts/generate-camera-specs.py from the C++ reference; do not edit by hand.",
        "",
        "namespace ColmapSharp.Sensor;",
        "",
        "public static partial class CameraSpecs",
        "{",
        f"\tprivate static void AddMakes{index}(List<CameraMakeSpecs> specs)",
        "\t{",
    ]
    for make, models in makes:
        lines.append(f"\t\tspecs.Add(new CameraMakeSpecs(\"{make}\", [")
        for model, width in models:
            lines.append(f"\t\t\tnew(\"{model}\", {width}),")
        lines.append("\t\t]));")
    lines += ["\t}", "}", ""]
    (OUT_DIR / f"CameraSpecs.Data{index}.cs").write_text("\n".join(lines))


def main():
    makes = parse(SOURCE.read_text())
    for old in OUT_DIR.glob("CameraSpecs.Data*.cs"):
        old.unlink()
    chunks = chunk(makes)
    for index, part in enumerate(chunks, start=1):
        write_chunk(index, part)
    print(f"{len(makes)} makes, {sum(len(m) for _, m in makes)} models, {len(chunks)} files")
    print("AddMakes calls: " + ", ".join(f"AddMakes{i}" for i in range(1, len(chunks) + 1)))


if __name__ == "__main__":
    main()
