#!/usr/bin/env python3
# Copyright (c) 2026, Lars Brubaker. MIT licensed (see LICENSE).
#
# Converts COLMAP's generated headers essential_matrix_poly.h and essential_matrix_coeffs.h
# (included into EssentialMatrixFivePointEstimator::Estimate's non-minimal path) into C#
# partial-class files under ColmapSharp/Estimators/Solvers/. The statements are copied
# verbatim - same operands, same order, so the rounding is the same - and only re-indented;
# `a`, `e`, `e2`, `e3` and `b` become span parameters, `coeffs(i)` becomes `coeffs[i]` and
# literals like `3.` become `3.0`.
# The polynomial matrix is split into several methods so every file stays under the
# 800-non-empty-line limit.
#
# Usage: scripts/generate-essential-matrix-poly.py [cpp-reference dir]  (after
# scripts/fetch-reference.sh)

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
# The reference checkout; pass another cpp-reference path as the first argument (a
# worktree checkout has none of its own).
REF = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "cpp-reference"
SRC = REF / "src/colmap/estimators/solvers"
OUT = ROOT / "ColmapSharp/Estimators/Solvers"

MAX_BODY_LINES = 700

HEADER = """// Copyright (c) 2026, Lars Brubaker. MIT licensed (see LICENSE).
// Ported from COLMAP (BSD-3-Clause, see THIRD_PARTY_NOTICES.md).
//
// GENERATED by scripts/generate-essential-matrix-poly.py from
// colmap/estimators/solvers/{source}. Do not edit by hand; rerun the script.
//
// {what}
// Called from EssentialMatrixEstimators.cs (the over-determined five-point path).

namespace ColmapSharp.Estimators.Solvers;

internal static partial class EssentialMatrixPolynomials
{{
"""


def statements(path, marker):
    """The assignment statements after `marker`, each a list of stripped source lines."""
    lines = path.read_text().splitlines()
    start = next(i for i, line in enumerate(lines) if marker in line)
    body = []
    current = []
    for line in lines[start + 1:]:
        stripped = line.strip()
        if not stripped or stripped == "}":
            continue
        current.append(stripped)
        if stripped.endswith(";"):
            body.append(current)
            current = []
    assert not current, "unterminated statement"
    return body


def emit(stmt):
    out = []
    for k, line in enumerate(stmt):
        line = re.sub(r"coeffs\((\d+)\)", r"coeffs[\1]", line)
        # C++ float literals like `3.` need a digit after the point in C#.
        line = re.sub(r"(\d)\.(?!\d)", r"\1.0", line)
        out.append(("\t\t" if k == 0 else "\t\t\t") + line)
    return out


def write(name, source, what, methods):
    text = HEADER.format(source=source, what=what)
    text += "\n\n".join(methods)
    text += "}\n"
    (OUT / name).write_text(text)


def main():
    poly = statements(SRC / "essential_matrix_poly.h", "e3[i] = e2[i] * e[i];")
    chunks = []
    current = []
    count = 0
    for stmt in poly:
        if count + len(stmt) > MAX_BODY_LINES and current:
            chunks.append(current)
            current = []
            count = 0
        current.append(stmt)
        count += len(stmt)
    chunks.append(current)

    for index, chunk in enumerate(chunks, start=1):
        body = [line for stmt in chunk for line in emit(stmt)]
        method = (
            f"\t/// <summary>Part {index} of {len(chunks)} of the 10 x 20 polynomial matrix A: the\n"
            f"\t/// verbatim assignments of essential_matrix_poly.h. <paramref name=\"a\"/> is A\n"
            f"\t/// column-major; <paramref name=\"e\"/> is the 9 x 4 null-space basis E\n"
            f"\t/// column-major, with <paramref name=\"e2\"/> and <paramref name=\"e3\"/> its\n"
            f"\t/// element-wise squares and cubes.</summary>\n"
            f"\tinternal static void FillPolynomialMatrixPart{index}(\n"
            f"\t\tSpan<double> a, ReadOnlySpan<double> e, ReadOnlySpan<double> e2, ReadOnlySpan<double> e3)\n"
            "\t{\n" + "\n".join(body) + "\n\t}\n")
        write(f"EssentialMatrixPolynomials.Poly{index}.cs",
              "essential_matrix_poly.h",
              f"Part {index} of {len(chunks)} of the coefficients of the ten cubic constraints\n"
              "// (the determinant and the trace constraint 2 E E^T E - tr(E E^T) E = 0) on the\n"
              "// null-space combination x E0 + y E1 + z E2 + E3 (Nister, PAMI 2004).",
              [method])

    coeffs = statements(SRC / "essential_matrix_coeffs.h", "const double* b = B.data();")
    body = [line for stmt in coeffs for line in emit(stmt)]
    method = (
        "\t/// <summary>The 11 coefficients of the tenth-degree determinant polynomial of the\n"
        "\t/// 3 x 3 polynomial matrix B: the verbatim assignments of essential_matrix_coeffs.h.\n"
        "\t/// <paramref name=\"b\"/> is the 13 x 3 matrix B column-major.</summary>\n"
        "\tinternal static void ComputeDeterminantCoefficients(ReadOnlySpan<double> b, Span<double> coeffs)\n"
        "\t{\n" + "\n".join(body) + "\n\t}\n")
    write("EssentialMatrixPolynomials.Coeffs.cs",
          "essential_matrix_coeffs.h",
          "The tenth-degree polynomial in z whose roots are the solutions (Nister's equation 14).",
          [method])
    print(f"{len(chunks)} polynomial parts, {len(poly)} + {len(coeffs)} statements")


if __name__ == "__main__":
    main()
